
**Завдання**

**1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.**

Імпортуємо бібліотеку NumPy

In [ ]:
import numpy as np

1.1. Задаємо розмір масиву

In [ ]:
size = 11

1.2. Створюємо нульовий масив заданого розміру

In [ ]:
array = np.zeros([size, size])

1.3 Друкуємо створений масив

In [ ]:
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


1.4 Змінюємо діагоналі за допомогою двох циклів

In [ ]:
for k in range(size):
	for n in range(size):
		if (k==n):
			array[k][n] = 1
		elif (n==size-k-1):
			array[n][k] = 1

1.5 Виводимо створений масив

In [ ]:
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).**

**Горизонтальний градієнт**


2.1 Створюємо нульовий масив розміром 255х255

In [ ]:
import cv2
import numpy as np

size = 255
horizontal_gradient1 = np.zeros([size, size])


2.2 Визначаємо розміри масиву

In [ ]:
w = horizontal_gradient1.shape[1]
h = horizontal_gradient1.shape[0]

2.3 Поелементно змінюємо яскравість кожного пікселя

In [ ]:
for k in range(size):
    for n in range(size):
        horizontal_gradient1[n][k] = k


2.4 Записуємо зображення засобами OpenCV

In [ ]:
cv2.imwrite('intro_to_numpy.jpg', horizontal_gradient1)

True

2.5 Аналогічно створюємо горизонтальний градієнт в інший бік

In [ ]:
size = 255
horizontal_gradient2 = np.zeros([size, size])

w = horizontal_gradient2.shape[1]
h = horizontal_gradient2.shape[0]
for i in range(size):
    for j in range(size):
        horizontal_gradient2[size-1-j][size-1-i] = i
        
cv2.imwrite('intro_to_numpy1.jpg', horizontal_gradient2)

True

**Вертикальний градієнт**


2.6 Створюємо нульовий масив розміром 255х255

In [ ]:
vertical_grad = np.zeros([size, size])


2.7 Визначаємо розміри масиву

In [24]:
w = vertical_grad.shape[1]
h = vertical_grad.shape[0]
for j in range(size):
    for i in range(size):
        horizontal_gradient2[size-1-j][size-1-i] = j

cv2.imwrite('ex1.jpg', vertical_grad)

True